variable "training_vpc_cidr" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "public_subnets_2" {}
variable "private_subnets_2" {}
variable "AWS_ACCESS_KEY" {}
variable "AWS_SECRET_KEY" {}
variable "AWS_REGION" {}
variable "user_ssh" {}
variable "PATH_KEYPAIR" {}
variable "PATH_PUBLIC_KEYPAIR" {}
variable "DATABASE_PASSWORD" {}
variable "DATABASE_USER" {}